# Generated by Django 3.1.2 on 2020-10-02 04:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLevel0',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('iso_3166_alpha_3', models.CharField(max_length=3)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'admin_level_0',
            },
        ),
        migrations.CreateModel(
            name='AdminLevel1',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('iso_3166_alpha_3', models.CharField(max_length=3)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'admin_level_1',
            },
        ),
        migrations.CreateModel(
            name='AdminLevel2',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('iso_3166_alpha_3', models.CharField(max_length=3)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'admin_level_2',
            },
        ),
        migrations.CreateModel(
            name='AdminLevel3',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('iso_3166_alpha_3', models.CharField(max_length=3)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'admin_level_3',
            },
        ),
        migrations.CreateModel(
            name='AdminLevel4',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('iso_3166_alpha_3', models.CharField(max_length=3)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'admin_level_4',
            },
        ),
        migrations.CreateModel(
            name='AdminLevel5',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('iso_3166_alpha_3', models.CharField(max_length=3)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'admin_level_5',
            },
        ),
    ]
