# Generated by Django 3.1.2 on 2020-10-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20201003_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlevel1',
            name='iso',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
