# Generated by Django 3.1.2 on 2020-10-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20201003_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlevel2',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
