# Generated by Django 3.1.2 on 2020-10-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_auto_20201003_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlevel2',
            name='iso_3166_alpha_3',
        ),
        migrations.RemoveField(
            model_name='adminlevel3',
            name='iso_3166_alpha_3',
        ),
        migrations.RemoveField(
            model_name='adminlevel4',
            name='iso_3166_alpha_3',
        ),
        migrations.RemoveField(
            model_name='adminlevel5',
            name='iso_3166_alpha_3',
        ),
        migrations.AddField(
            model_name='adminlevel2',
            name='iso',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='adminlevel3',
            name='iso',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='adminlevel4',
            name='iso',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='adminlevel5',
            name='iso',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
