# Generated by Django 3.1.2 on 2020-10-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_auto_20201003_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlevel0',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
